"""empty message

Revision ID: 1c6f67f68171
Revises: 
Create Date: 2022-02-07 12:35:28.255290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c6f67f68171'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pal_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pal_id')
    )
    op.create_table('pal',
    sa.Column('friendship_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('adding_pal', sa.Integer(), nullable=False),
    sa.Column('added_pal', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['added_pal'], ['pet.pal_id'], ),
    sa.ForeignKeyConstraint(['adding_pal'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('friendship_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pal')
    op.drop_table('pet')
    # ### end Alembic commands ###
