"""empty message

Revision ID: 59f70e7999b1
Revises: 
Create Date: 2022-02-02 17:45:22.418977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f70e7999b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('pet_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('pet_id')
    )
    op.create_table('friendship',
    sa.Column('friendship_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pal_id', sa.Integer(), nullable=False),
    sa.Column('potential_pals', sa.Boolean(), nullable=True),
    sa.Column('pending_pals', sa.Boolean(), nullable=True),
    sa.Column('pawsitively_pals', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pal_id'], ['pet.pet_id'], ),
    sa.PrimaryKeyConstraint('friendship_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendship')
    op.drop_table('pet')
    # ### end Alembic commands ###
