"""empty message

Revision ID: 69ddfa3872c6
Revises: 
Create Date: 2022-02-01 17:51:26.113166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ddfa3872c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friendship', 'pal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('pet', sa.Column('phone_number', sa.Integer(), nullable=False))
    op.drop_column('pet', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('phone', sa.NUMERIC(precision=9, scale=0), autoincrement=False, nullable=False))
    op.drop_column('pet', 'phone_number')
    op.alter_column('friendship', 'pal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
