"""empty message

Revision ID: b65a9bc9b031
Revises: 69ddfa3872c6
Create Date: 2022-02-01 17:55:11.175894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65a9bc9b031'
down_revision = '69ddfa3872c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('phone', sa.Numeric(precision=9), nullable=False))
    op.drop_column('pet', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('phone_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('pet', 'phone')
    # ### end Alembic commands ###
